package com.register.app.util

const val ADMIN_CHAT = "admin_chat/{remoteUserEmail}"
const val HOME = "home"
const val GROUP_NOTIFICATIONS = "group_notifications"
const val ALL_USER_ACTIVITIES = "all_user_activities"
const val DIRECT_CHAT = "direct_chat"
const val NOTIFICATIONS = "notifications"
const val ASSIGN_LEVY = "assign_very"
const val PAY_SPECIAL_LEVY = "pay_special_levy"
const val SPECIAL_LEVY_DETAIL = "special_levy_detail"
const val BATCH_UPLOAD = "batch_upload"
const val BATCH_UPLOAD_INTRO = "batch_upload_intro"
const val EVENT_DETAIL = "event_detail"
const val SETTINGS = "settings"
const val ONBOARDING = "onboarding"
const val PRIVACY = "privacy_policy"